controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reclamation_piece_jointe:
    path: '/uploads/reclamations/{filename}'
    controller: App\Controller\ReclamationController::getPieceJointe
    requirements:
        filename: '.+'